name = "DynamicalSystems"
uuid = "524d30e7-1f8a-489f-98dd-7b68cdbbb39b"
authors = ["nish <nishs1729@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
